options/options.css
options/options.html
options/options.js
popup/popup.css

- Adds import & export functionality for link patterns. Link patterns are imported/exported as JSON. 
- Patterns can be imported in `Append` or `Overwrite` modes. 
- Adds RegEx validation on manual input and file import. This prevents breaking the extension from loading when an invalid RegEx pattern is saved. 
- Adds stylesheet to options page (now a darker colour scheme).
Resolves #14

Add bulk JSON import & export for link patterns

---

popup/popup.css

Fix horizontal overflow and anchor the `Links` and `Attachments` tabs to the top of the UI.
This PR also fixes the automatic height and width values of the extension. I also made `max-width` of the extension slightly wider.

Fix horizontal overflow, and anchor the `Links` and `Attachments` tabs

---

popup/popup.js

This PR fixes HTML tags showing in the links lists.
Example:
Before: `This is a <em>strong</em> sentence with <code>code blocks</code>.`
Now: `This is a strong sentence with code blocks`
Resolves #13

Fix HTML tags showing in the links lists when link has child elements.

---

content-scripts/contentscript.js
popup/popup.js

This PR adds support for Zendesk Agent Workspace. 
The agent workspace uses different attributes to tie [the comment JSON data](https://developer.zendesk.com/api-reference/ticketing/tickets/ticket_comments/#list-comments) to the HTML in the ticket. This linkage is required to properly scroll to elements in either version of the ticket view.
Old Zendesk views:
HTML `data-comment-id` attribute -> `id` JSON key. 
Agent Workspace:
HTML `id` attribute -> `audit_id` JSON key

Add Agent Workspace compatibility for scroll-to functionality

---

popup/popup.css
popup/popup.js

This PR adds the `title` attribute to links. This allows you to see the link `href` (the URL) while hovering over the link.

Add tooltip hover for links in extension UI

---

src/options/options.css
src/options/options.html

Add tooltips explaining the different fields to options page.
Example:
Resolves #35

Add tooltips explaining the different fields to options page

---

src/popup/popup.css
src/popup/popup.html
src/popup/popup.js

- Adds a button to copy individual links to the clipboard in markdown format. Resolves #40 
- Duplicate links (duplicate `href` values) are now removed from the extension UI and the markdown summary. The most recent occurrence of the link is kept. Related to #42 
- Add tooltip popup to summary button.
- Add comment creation date to each link's tooltip.

Add copy link to markdown button, and start removing duplicates from found links

---

src/content-scripts/contentscript.js

Add a last resort option to ensure "scroll to comment" functionality works in Zendesk's Agent Workspace. 
Sometimes Zendesk will not put comment or audit IDs in the ticket's HTML, making this "fast" method of scrolling impossible.
To ensure we can always scroll to the comment, the extension will now fall back to this behavior when it can't find an element to scroll to, based on either the comment or audit ID: 
- Using the `audits` API endpoint, get the audit events associated with the comment's audit ID.
- Scroll to the first comment that exactly matches the HTML of an audit event of type `comment`.
This will involve a slight delay, because the audit API endpoint must be called when the scroll button is clicked.

Add fallback option for "scroll to comment" feature to more consistently scroll to comments across all Zendesk workspace types

---

.gitignore
makefile
src/manifest-chrome.json
src/manifest-firefox.json
src/manifest.json

- Split manifests for browsers.
- Each manifest now has 2 versions for each browser.
- A default manifest.json will remain in `src` for development purposes (chrome only).
- Introduce makefile to easily build for each browser. This copies the extension to a `build` subfolder and renames the brows-specific manifest file to `manifest.json`.
Resolves #19

Split manifests for different browsers, allowing the development of background tasks (custom keybinds and other browser-specific features)

---

src/background/background.js
src/popup/popup.css

This PR updates the comment sorting order in the background.js file to descending order. It also changes the list layout in the popup.css file to display items in a column instead of a reverse column.
Instead of sorting with CSS, we'll now sort with the request parameter.
This commit also fixes a bug with sorting in the configurable summary output since the data itself is now sorted.

FIX: Refactor comment sorting order mechanism and markdown summary output order

---

src/background/background.js
src/content-scripts/contentscript.js
src/popup/popup.css
src/popup/popup.html
src/popup/popup.js

- Created a new "Images" tab to store image type attachments.
- Image previews are shown in the "Image" instead of links.
- Clicking on an image preview opens it in Zendesk's native image preview.
- Scrolling to the image is possible, as usual.
- Removed image type files from the "Attachments" tab.
Closes #54 
Closes #9

Add new "Images" tab for image attachment types

---

src/popup/popup.css
src/popup/popup.html

This pull request primarily focuses on improving the user interface and user experience of the application.
In addition to the new button, there are some other minor UI changes:
- Increasing the minimum width of the container
- Updating the message displayed when no images are found
- Removing a comment in the CSS file. 
Closes #36

Add "what's new?" button that links to release notes

---

src/background/background.js
src/content-scripts/contentscript.js
src/manifest-chrome.json
src/manifest-firefox.json
src/manifest.json

This pull request adds support for new keyboard shortcuts for copying ticket IDs: 
- Copy ticket ID to clipboard
- Copy ticket link in markdown to clipboard
These changes are primarily in the `src/background/background.js` and `src/content-scripts/contentscript.js` files, but also include updates to the manifest files for Chrome, Firefox, and a generic manifest file.

Add keyboard shortcuts to copy ticket ID and copy ticket link in markdown

---

src/popup/popup.html
src/popup/popup.js

Display version number instead of "What's new?" text and link to the specific release notes for the installed version instead of just a hard-coded link to the latest. 
Closes #58

Display version number instead of "What's new?" text. 

---

src/background/background.js

This change replaces the use of var declarations with let or const, ensuring better scoping and immutability respectively, which leads to cleaner, more predictable code and helps prevent unintended variable reassignments or scope leaks.
Closes: #60

Replace var declarations with let or const

---

src/background/background.js
src/options/options.html
src/options/options.js
src/popup/popup.css
src/popup/popup.js

This PR adds an option under each link pattern to display the source comment's date beside the link in the extension popup.
Closes #51 
- Clicking the date text will copy the date to the clipboard in UTC. 
- The cursor hover image is now a zoom icon for images in the images tab. 
- This PR also fixes a bug where Summary Type and Show Dates options would be incorrectly overwritten for identical filter patterns.
Functional enhancements:
* [`src/background/background.js`](diffhunk://#diff-d7072b9c615837a7b1318ff38a6dda1ea436aeb0b8fc073d1b32e52b73378937L222-R227): Modified the `filterTicket()` function to create a new object `link2Push` from the current `link` object and added `summaryType` and `showDate` properties to `link2Push` before pushing it to `filteredLinksArr`. This change enhances …

Add option to include date in links

---

src/background/background.js
src/options/options.css
src/options/options.html
src/options/options.js

This pull request adds the ability to edit existing link patterns in the options page. 
Closes #50 
User Interface Changes:
* [`src/options/options.css`](diffhunk://#diff-0f6ed38497050661f6aaf383e9697bc64c4423c1828830f2a1c2d2cce7d89d6fR28-R36): Added styles for disabled buttons and rows being edited in the link patterns table. [[1]](diffhunk://#diff-0f6ed38497050661f6aaf383e9697bc64c4423c1828830f2a1c2d2cce7d89d6fR28-R36) [[2]](diffhunk://#diff-0f6ed38497050661f6aaf383e9697bc64c4423c1828830f2a1c2d2cce7d89d6fR118-R121)
* [`src/options/options.html`](diffhunk://#diff-594c44a28df5453d166af1cfc08191e04d1a2576a04161c773b2ea80e2dac86cR49): Added a new column in the link patterns table for the 'Edit' action.
JavaScript Functionality Changes:
* …

Feature: in-place link pattern editing

---

src/popup/popup.css
src/popup/popup.html
src/popup/popup.js

This PR adds two new buttons to copy attachments and images to clipboard in markdown format. 
Closes #66

Add buttons to copy attachments and images to clipboard in markdown format

---

src/background/background.js
src/options/options.html
src/options/options.js
src/popup/popup.js

This PR adds new options to include attachments and/or images in markdown summary to the options page. 
These options will be on by default.

Feature: new options to include attachments and/or images in markdown summary

---

src/content-scripts/contentscript.js

Highlight the comment being scrolled to make it easier to see what comment you are scrolling to.
This PR also addresses an issue where the scroll-to comment could have sent multiple responses to the background script/popup script, making one of the messages return an exception.
Closes #63

Add visual scroll-to comment indicator

---

README.md
samples/link-patterns.json
src/background/background.js
src/options/options.html

Enhancements to user experience:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R18): Added a section about downloading a sample JSON file for link patterns to help users understand the format.
* [`src/options/options.html`](diffhunk://#diff-594c44a28df5453d166af1cfc08191e04d1a2576a04161c773b2ea80e2dac86cR43-R48): Added a section to display example patterns for users to understand how they can be written.
Functionality improvements:
* [`src/background/background.js`](diffhunk://#diff-d7072b9c615837a7b1318ff38a6dda1ea436aeb0b8fc073d1b32e52b73378937L347-R347): Updated the extension installation process to set default link patterns. It also checks if patterns from a previous installation exist before overwriting them. …

Add example and default link patterns to extension UI and readme
